export const ABBREVIATIONS: any = {
  GTG: 'Gotta go',
  LMAO: 'Laughing my ass off',
  LMFAO: 'Laughing my fuicking ass off',
  OMW: 'On my way',
  OMG: 'Oh my god',
  ROFL: 'Rolling on floor laughing',
  STFU: 'Shut the fuck up',
  ICYMI: 'In case you missed it',
  TLDR: "Too long, didn't read",
  LMK: 'Let me know',
  NVM: 'Nevermind',
  TGIF: "Thank goodness it's Friday",
  TBH: 'To be honest',
  TBF: 'To be frank',
  RN: 'Right now',
  QOTD: 'Quote of the day',
  OOTD: 'Outfit of the day',
  BRB: 'Be right back',
  BTW: 'By the way',
  LOL: 'Laugh out loud',
  TTYL: 'Talk to you later',
  HMU: 'Hit me up',
  FWIW: "For what it's worth",
  IMO: 'In my opinion',
  IMHO: 'In my humble opinion',
  IDK: "I don't know",
  TBA: 'To be announced',
  TBD: 'To be decided',
  EOD: 'End of day',
  FAQ: 'Frequently asked question',
  AKA: 'Also known as',
  ASAP: 'As soon as possible',
  DIY: 'Do it yourself',
  LMGTFY: 'Let me Google that for you',
  NP: 'No problem',
  'N/A': 'Not applicable or not available',
  TIA: 'Thanks in advance',
  ILY: 'I love you',
  ILHA: 'I love Hong Anh',
  MCM: 'Man crush Monday',
  WCW: 'Woman crush Wednesday',
  BF: 'Boyfriend',
  GF: 'Girlfriend',
  CTA: 'Call to action',
  UGC: ' User-generated content',
  SMS: 'Short message service',
  MMS: 'Multimedia messaging service',
  RCS: 'Rich communication services',
  ROI: 'Return on investment',
  CTR: 'Click-through rate',
  MIA: 'Mising from action',
};
